language: node_js
node_js:
  - '9'

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "datacl"
  - git config user.email "527423296@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - datacl-source
env:
 global:
   - GH_REF: github.com/datacl/datacl.github.io.git
